### ISSUE TITLE
NuGet not available

### ISSUE THREAD

**Issue by SuperJMN** [Genbox/VelcroPhysics#58] opened 2019-10-09 12:08 UTC
Hey hello! 

Is there any plan to release a NuGet package of this project? 
Thanks

**Comment by Genbox** [comment] 2019-10-09 20:27
Yes. I want to target .NET Standard 2.0 and release a nuget package, but everything halted to a standstill because MonoGames have not moved to .NET Core yet. I'm also working on other projects right now, so the code in this repo is not quite there yet.

**Comment by SuperJMN** [comment] 2019-10-10 11:33
@Genbox thanks for you quick response! I would like to take a look to the PR I've sent. I could help with the NuGet packages if you wish. 

Best regards!

**Comment by Genbox** [comment] 2019-10-11 17:55
Thanks! I'll check it out.

**Comment by SuperJMN** [comment] 2021-04-04 11:09
MonoGame is already .NET Standard! Will we get Nuget packages anytime soon? 😊

**Comment by ambs** [comment] 2021-04-18 20:27
Looking forward to a NuGet package. It would allow me to use this library with my students more easily.

**Comment by Genbox** [comment] 2021-04-18 22:01
There are still a lot of things not working right within the engine, so consider it alpha state for now. Nuget package is coming asap.

**Comment by ambs** [comment] 2021-04-19 09:17
@Genbox Of course. But at least is looks like it is maintained. Chipmunk was my other choice and... forget it :-)

**Comment by Genbox** [comment] 2021-04-20 14:38
Packages are up:
- .NET Standard: https://www.nuget.org/packages/Genbox.VelcroPhysics/
- MonoGame: https://www.nuget.org/packages/Genbox.VelcroPhysics.MonoGame/

Let me know if they work as intended.

@SuperJMN could you unlist your packages on Nuget? Don't want a lot of support questions about which packages to use :)

**Comment by ambs** [comment] 2021-04-20 14:44
When I try to use it directly on a Monogame project, bootstrapped using the `dontnet mgdekstopgl` template, I get:
```
error: Unable to find a stable package Genbox.VelcroPhysics.MonoGame with version (>= 0.0.0)
error:   - Found 1 version(s) in nuget.org [ Nearest version: 0.1.0-alpha ]
error: Package 'Genbox.VelcroPhysics.MonoGame' is incompatible with 'all' frameworks in project '/home/ambs/tmp/CM/CM.csproj'.
```
My `.csproj` here: https://gist.github.com/ambs/cda443d905f8527494fd84423d126dab

Thanks

**Comment by Genbox** [comment] 2021-04-20 15:32
It is an alpha package, so you have to enable support for those. I've found the easiest way is to just add the PackageReference manually to the csproj file:

`<PackageReference Include="Genbox.VelcroPhysics" Version="0.1.0-alpha" />`

Or you can use the Nuget Package Manager, but remember to put a check in the "Include prerelease" checkbox.

![image](https://user-images.githubusercontent.com/657616/115423703-5719b600-a1fe-11eb-9b7f-2b3a00dda5c6.png)

**Comment by ambs** [comment] 2021-04-22 16:05
This worked:
`dotnet add package Genbox.VelcroPhysics -v 0.1.0-alpha`

now I need time to read the tutorial :)

**Comment by Genbox** [comment] 2021-04-24 16:43
Sounds good. Closing this issue.

**Closed by Genbox** 2021-04-24 16:43 UTC
